### ISSUE TITLE
php are missing

### ISSUE THREAD

**Issue by TRC4** [kishor10d/feedbacker#1]
some php are missing in /application/views/  as dashboard.php summaryReport.php etc

**Comment by almohajire** [comment]
Try this , it works for me
https://github.com/kishor10d/Admin-Panel-User-Management-using-CodeIgniter/blob/master/application/views/dashboard.php

**Comment by kishor10d** [comment]
@TRC4 : Hey, ```dashboard.php``` added, summaryReport.php is under development. I will update you soon.
