### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by bayjohnpaul** [kishor10d/feedbacker#3]
Hi @kishor10d, I would like to create a registration page for this project is it fine with you?

**Comment by bayjohnpaul** [comment]
I would like to add some css if it's going to be alright

**Comment by kishor10d** [comment]
@bayjohnpaul : Actually its will be internal project for any organization. No one want's to register users other than organization.
Please develop it at your fork and please follow the rules codeigniter mvc pattern and then create the registration page.
